### ISSUE TITLE
Porsche 911 RWB (993)

### ISSUE THREAD

**Issue by ghost** [wear87/CSR2-Racing-Collection#1]
Oil color with gold livery and wheels.
[oil (2).txt](https://github.com/wear87/CSR2-Racing-Collect/files/4624098/oil.2.txt)

**Comment by ghost** [comment]
In the original Crew Championship Milestone livery.

**Comment by wear87** [comment]
Received, updated, thanks for the reminder

**Comment by wear87** [comment]
> Oil color with gold livery and wheels.
> [oil (2).txt](https://github.com/wear87/CSR2-Racing-Collect/files/4624098/oil.2.txt)

Thank you for your reminder. An update has been added.
