### ISSUE TITLE
Car files

### ISSUE THREAD

**Issue by AppletvApp** [wear87/CSR2-Racing-Collection#10]
Trying to learn a quick option to search and find any car file in game preferably with full fusion n stg6ers if possible .. I have certain update lists but can't find the odds n ends of every tier help plz

**Comment by wear87** [comment]
> 尝试学习一个快速选项来搜索和查找游戏中的任何汽车文件，如果可能的话，最好使用全融合 n stg6ers .. 我有某些更新列表，但找不到每一层帮助的可能性 n

Is it convenient to send me an email ？ ：hotlibo87@gmail.com

**Comment by AppletvApp** [comment]
I’m trying to find a easy way to search for any car file in the game no matter how old and then I’m trying to find out is there a pre ready template for changing the cars to maxed bi applying the file for the specific tier n number of parts that gets pasted into the car file in place of the stock parts data if so can I get link to the part files for maxing the specific car tiers and parts ammount etc and do I simply just type the name of the car file I want in search on the Csr2 GitHub?
________________________________
