### ISSUE TITLE
Mo Die Sse 

### ISSUE THREAD

**Issue by miciomaxx** [wear87/CSR2-Racing-Collection#4]
waiting 2.17 commits... if none can do it, add me please

**Comment by wear87** [comment]
If you are interested, welcome to my group.

**Comment by D-A-G16** [comment]
Thanks man, but, what group?

**Comment by miciomaxx** [comment]
> If you are interested, welcome to my group.

I'm moderator in your group... ;-) @wear87 I'm Mo DieSse

**Comment by D-A-G16** [comment]
Huh, really? Well, i didn't know, but... what group are you talking about?

**Comment by ysterperd777** [comment]
Hi wear87 and Mo DieSse,

I'm not too sure what's going on here. Please enlighten me?

BTW, while we're on the topic of the GitHub repo, I'd love to be a
collaborator on the repo.

Regards,
Ysterperd
