### ISSUE TITLE
Ultima RS Gold 5* isn’t available 

### ISSUE THREAD

**Issue by AyushKenhi** [wear87/CSR2-Racing-Collection#9]
[Ultima_RSGold_2020.txt](https://github.com/wear87/CSR2-Racing-Collection/files/6629696/Ultima_RSGold_2020.txt)

**Comment by wear87** [comment]
Thanks for your feedback, the new file is ready and will be uploaded and updated in a few days.

**Comment by wear87** [comment]
> [Ultima_RSGold_2020.txt](https://github.com/wear87/CSR2-Racing-Collection/files/6629696/Ultima_RSGold_2020.txt)

Thanks for your feedback, the new file is ready and will be uploaded and updated in a few days.
